// Import ABIs (auto-generated by scripts/fetchABI.ts)
export { token1ABI } from '../abis/token1ABI';

// Farcaster-supported chain IDs for swap functionality
export const FARCASTER_SUPPORTED_CHAINS = [
  1,      // Ethereum Mainnet
  8453,   // Base
  10,     // Optimism
  42161,  // Arbitrum
  137,    // Polygon
  7777777, // Zora
  130,    // Unichain
  100,    // Gnosis
  56,     // BNB Chain (BSC)
  43114,  // Avalanche C-Chain
  42220,  // Celo
] as const;

// Contract addresses by chain ID
// Note: This app only supports Celo (42220) for game contracts
// Swap/bridge functionality may support other chains
const CONTRACT_ADDRESSES = {
  // Celo (Mainnet) - Primary and only supported chain for game contracts
  42220: {
    token1ContractAddress: "0xe05489dea86d85c32609410a1bF9C35a0f8fc2e7",
    quizGameContractAddress: "0x367c011DC980E695EdE1e314af0a82C7E2b01e3B",
    seasonRewardContractAddress: "0x49Cde09f1CE2A1C00ef1920BB7C0ae34F565524E",
    // BunnyGame contracts
    eggTokenContractAddress: "0x4FCf91f48d3888126ebaabc8fa698cd5cBCAD648",
    bunnyGameContractAddress: "0x0FdD3Cc0abB29B1baf1e901ca096e8AE3B43Ba51",
    retentionSystemContractAddress: "0x9B61AeB993dD8c75988C0CB2d4648224752D7267"
  }
} as const;

// Rewards configuration by chain ID
// Note: Only Celo (42220) is supported
const REWARDS_CONFIG = {
  // Celo (Mainnet) - Only supported chain
  42220: {
    totalReward: 250,
    currency: "CELO",
    symbol: "🟡",
    maxWinners: 30,
    seasonEndDate: new Date("2025-12-05T23:59:59Z") // Celo season ends December 5, 2025
  }
} as const;

// Function to get contract addresses by chain ID
export function getContractAddresses(_chainId: number) {
  // Only Celo (42220) is supported - return Celo addresses for any chain
  // This ensures the app always uses Celo contracts
  return CONTRACT_ADDRESSES[42220];
}

// Function to get rewards configuration by chain ID
export function getRewardsConfig(_chainId: number) {
  // Only Celo (42220) is supported - return Celo config for any chain
  return REWARDS_CONFIG[42220];
}

// Legacy exports removed - use getContractAddresses(chainId) instead

// Demo configuration
export const DEMO_CONFIG = {
  AUTO_PLAY_INTERVAL: 30000, // 30 seconds per step
  STEP_DURATION: {
    1: 20000, // Solo Quiz: 20 seconds
    2: 29000, // PvP Duel: 29 seconds  
    3: 29000, // Guild System: 29 seconds
    4: 26000  // NFT Quizzes: 26 seconds
  },
  MOCK_DATA: {
    ORACLE_PRICES: {
      ETH: { price: 2450.50, index: 1 },
      BASE: { price: 1.23, index: 2 }
    },
    GUILD_MEMBERS: [
      { name: "Alex", score: 850, avatar: "👤", fid: 12345 },
      { name: "Sarah", score: 720, avatar: "👩", fid: 23456 },
      { name: "Mike", score: 680, avatar: "👨", fid: 34567 },
      { name: "Emma", score: 590, avatar: "👱‍♀️", fid: 45678 }
    ]
  }
} as const;