#!/usr/bin/env npx tsx
/**
 * Fetch ABIs from compiled contracts and generate TypeScript files
 *
 * Usage:
 *   npx tsx scripts/fetchABI.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CONTRACTS_OUT_DIR = path.join(__dirname, '../contracts/out');
const LIBS_DIR = path.join(__dirname, '../src/libs');

// Contract configurations: [solFile, contractName, outputName]
const CONTRACTS = [
  ['BunnyGame.sol', 'BunnyGame', 'bunnyGameABI'],
  ['BunnyGame.sol', 'EggToken', 'eggTokenABI'],
  ['BunnyGame.sol', 'RetentionSystem', 'retentionSystemABI'],
  ['QuizGame.sol', 'QuizGame', 'quizGameABI'],
  ['QuizGame.sol', 'Token1', 'token1ABI'],
  ['SeasonReward.sol', 'SeasonReward', 'seasonRewardABI'],
];

interface ContractJSON {
  abi: any[];
  bytecode?: {
    object: string;
  };
  deployedBytecode?: {
    object: string;
  };
}

function readContractABI(solFile: string, contractName: string): any[] {
  const jsonPath = path.join(CONTRACTS_OUT_DIR, solFile, `${contractName}.json`);

  if (!fs.existsSync(jsonPath)) {
    throw new Error(`Contract JSON not found: ${jsonPath}`);
  }

  const contractData: ContractJSON = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  return contractData.abi;
}

function generateABIFile(outputName: string, abi: any[]): void {
  const content = `// Auto-generated by scripts/fetchABI.ts
// Do not edit manually - regenerate with: npx tsx scripts/fetchABI.ts

export const ${outputName} = ${JSON.stringify(abi, null, 2)} as const;
`;

  const outputPath = path.join(LIBS_DIR, `${outputName}.ts`);
  fs.writeFileSync(outputPath, content);
  console.log(`✓ Generated ${outputName}.ts`);
}

function main() {
  console.log('🔄 Fetching ABIs from compiled contracts...\n');

  // Ensure output directory exists
  if (!fs.existsSync(LIBS_DIR)) {
    fs.mkdirSync(LIBS_DIR, { recursive: true });
  }

  // Generate ABI files
  for (const [solFile, contractName, outputName] of CONTRACTS) {
    try {
      const abi = readContractABI(solFile, contractName);
      generateABIFile(outputName, abi);
    } catch (error) {
      console.error(`✗ Error processing ${contractName}:`, error instanceof Error ? error.message : error);
      process.exit(1);
    }
  }

  console.log('\n✅ All ABIs generated successfully!');
  console.log('\nGenerated files:');
  CONTRACTS.forEach(([, , outputName]) => {
    console.log(`  - src/libs/${outputName}.ts`);
  });
}

main();
